/// Flutter icons FontIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FontIcon
///      fonts:
///       - asset: fonts/FontIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FontIcon {
  FontIcon._();

  static const _kFontFam = 'FontIcon';

  static const IconData normal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData waring = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData danger = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData good = const IconData(0xe804, fontFamily: _kFontFam);
}
